version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./client:/usr/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "9999:9999"
    volumes:
      - ./server:/usr/app
