# Specify a base image
FROM python:3

WORKDIR /usr/app

# Install dependencies
RUN pip install virtualenv \
  && rm -rf /var/cache/apk/*

## Only reinstall deps if requirements.txt changed
COPY requirements.txt .
COPY requirements-dev.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

COPY . .
EXPOSE 9999

# Default command
CMD ["python", "socket_server.py"]
